### ISSUE TITLE
Lab 3

### ISSUE THREAD

**Issue by zaq007** [IvanSir/LabsCSharp#3]
В классе Vehicle есть вещи, которые никак не относятся к транспортному средству (работа с консолью, получение логического типа из строки)
Их нужно убрать

**Comment by IvanSir** [comment]
Исправил, добавил новый статический класс со вспомогательными методами( получение логического типа из строки, проверка ввода) - "Assist". Работу с консолью перенес в "MainClass". Все новые файлы с пометкой NEW

**Comment by zaq007** [comment]
Так как пятой лабы это тоже касается, лучше их объединить в одну

**Comment by IvanSir** [comment]
Исправил 5 лабораторную в "Lab5_CSharp" с пометкой New, также еще есть лабы 4,7 в pull request'e ( 6 пока не исправлял ).
